version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /www
    schedule:
      interval: daily
    versioning-strategy: 'increase-if-necessary'
