run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - nolintlint
    - tenv
    - varnamelen
    - godox
    - gochecknoglobals
    - gci
    - funlen
    - forcetypeassert
    - gofumpt
    - depguard
    - goimports
    - unused
    - dupl
    - stylecheck
    - interfacebloat
    - nestif
issues:
  exclude-dirs:
    - tmp
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - maintidx
        - dupl
        - cyclop
linters-settings:
  cyclop:
    max-complexity: 18
  maintidx:
    under: 17
  exhaustruct:
    exclude:
      - '.*Error$'  # Ignores any struct type ending with "Error"
  gomoddirectives:
    replace-allow-list:
      - github.com/swaggo/http-swagger/v2
