run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - nolintlint
    - tenv
    - varnamelen
    - mnd
    - lll
    - godox
    - gocritic
    - gochecknoglobals
    - gci
    - funlen
    - forcetypeassert
    - exhaustruct
    - gofumpt
    - depguard
    - goimports
    - cyclop
    - unused
    - gosec
    - dupl
    - stylecheck
    - maintidx
    - interfacebloat
    - nestif
issues:
  exclude-dirs:
    - tmp
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - maintidx
        - dupl
        - cyclop
