auth:
  adminUser: admin
  adminPassword: admin
extraEnvVars:
  - name: JAVA_OPTS
    value: "-XX:UseSVE=0" # For aarm64
extraVolumes: |
  - name: keycloak-theme-dir
    emptyDir: {}
extraVolumeMounts: |
  - name: keycloak-theme-dir
    mountPath: /opt/bitnami/keycloak/themes
keycloakConfigCli:
  enabled: true
  configuration:
    realm.json: |
      {
        "realm": "ketabdoozak",
        "displayName": "کتابدوزک",
        "enabled": true,
        "registrationAllowed": true,
        "resetPasswordAllowed": true,
        "clients": [
          {
            "clientId": "api",
            "name": "Auth Service",
            "publicClient": false,
            "secret": "api-secret",
          },
          {
            "clientId": "www",
            "name": "WWW Service",
            "baseUrl": "http://api-dev.ketabdoozak",
            "publicClient": false,
            "secret": "www-secret",
            "redirectUris": [
              "http://api-dev.ketabdoozak/*",
              "http://localhost:3000/*"
            ],
            "webOrigins": [
              "*"
            ]
          }
        ],
        "internationalizationEnabled": true,
        "supportedLocales": [
          "fa"
        ],
        "defaultLocale": "fa"
      }
