// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","termsOfService":"http://swagger.io/terms/","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/filemanager/files/{filename}":{"get":{"security":[{"OAuth2Implicit":[]}],"tags":["filemanager"],"summary":"Download a file","parameters":[{"type":"string","description":"Filename","name":"filename","in":"path","required":true}],"responses":{"307":{"description":"Temporary Redirect"}}},"delete":{"security":[{"OAuth2Implicit":[]}],"tags":["filemanager"],"summary":"Delete a file","parameters":[{"type":"string","description":"Filename","name":"filename","in":"path","required":true}],"responses":{"204":{"description":"No Content"}}}},"/filemanager/upload":{"post":{"security":[{"OAuth2Implicit":[]}],"consumes":["multipart/form-data"],"tags":["filemanager"],"summary":"Upload a file","parameters":[{"type":"file","description":"File key","name":"file","in":"formData","required":true}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/filemanager.File"}}}}}},"definitions":{"filemanager.File":{"type":"object","properties":{"contentType":{"type":"string"},"createdAt":{"type":"string"},"filename":{"type":"string"},"size":{"type":"integer"},"updatedAt":{"type":"string"}}}},"securityDefinitions":{"OAuth2Implicit":{"type":"oauth2","flow":"implicit","authorizationUrl":"https://auth.applicaset.com/realms/ketabdoozak/protocol/openid-connect/auth"}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Ketabdoozak",
	Description:      "This is ketabdoozak api doc",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
