definitions:
  filemanager.File:
    properties:
      contentType:
        type: string
      createdAt:
        type: string
      filename:
        type: string
      size:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: This is ketabdoozak api doc
  termsOfService: http://swagger.io/terms/
  title: Ketabdoozak
  version: "1.0"
paths:
  /filemanager/files/{filename}:
    delete:
      parameters:
      - description: Filename
        in: path
        name: filename
        required: true
        type: string
      responses:
        "204":
          description: No Content
      security:
      - OAuth2Implicit: []
      summary: Delete a file
      tags:
      - filemanager
    get:
      parameters:
      - description: Filename
        in: path
        name: filename
        required: true
        type: string
      responses:
        "307":
          description: Temporary Redirect
      security:
      - OAuth2Implicit: []
      summary: Download a file
      tags:
      - filemanager
  /filemanager/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: File key
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/filemanager.File'
      security:
      - OAuth2Implicit: []
      summary: Upload a file
      tags:
      - filemanager
securityDefinitions:
  OAuth2Implicit:
    authorizationUrl: https://auth.applicaset.com/realms/ketabdoozak/protocol/openid-connect/auth
    flow: implicit
    type: oauth2
swagger: "2.0"
