CREATE TABLE listing_locations
(
    id        VARCHAR NOT NULL PRIMARY KEY,
    title     VARCHAR NOT NULL,
    parent_id VARCHAR NOT NULL DEFAULT ''
);

INSERT INTO listing_locations (id, title, parent_id)
VALUES ('tehran', 'تهران', ''),
       ('mashhad', 'مشهد', ''),
       ('isfahan', 'اصفهان', ''),
       ('tabriz', 'تبریز', ''),
       ('shiraz', 'شیراز', ''),
       ('ahvaz', 'اهواز', ''),
       ('qom', 'قم', ''),
       ('kermanshah', 'کرمانشاه', ''),
       ('rasht', 'رشت', ''),
       ('karaj', 'کرج', ''),
       ('urmia', 'ارومیه', ''),
       ('zahedan', 'زاهدان', ''),
       ('hamadan', 'همدان', ''),
       ('kerman', 'کرمان', ''),
       ('ardebil', 'اردبیل', ''),
       ('yazd', 'یزد', ''),
       ('bandarabbas', 'بندرعباس', ''),
       ('arak', 'اراک', ''),
       ('bushehr', 'بوشهر', ''),
       ('sanandaj', 'سنندج', ''),
       ('zanjan', 'زنجان', ''),
       ('gorgan', 'گرگان', ''),
       ('sari', 'ساری', ''),
       ('khorramabad', 'خرم‌آباد', ''),
       ('birjand', 'بیرجند', ''),
       ('bojnourd', 'بجنورد', ''),
       ('shahrekord', 'شهرکرد', ''),
       ('ilam', 'ایلام', ''),
       ('yasuji', 'یاسوج', ''),
       ('shahrud', 'شاهرود', ''),
       ('qazvin', 'قزوین', ''),
       ('saveh', 'ساوه', ''),
       ('nishapur', 'نیشابور', ''),
       ('najafabad', 'نجف‌آباد', ''),
       ('kashan', 'کاشان', ''),
       ('borujerd', 'بروجرد', ''),
       ('malayer', 'ملایر', ''),
       ('dezful', 'دزفول', ''),
       ('sabzevar', 'سبزوار', ''),
       ('amol', 'آمل', ''),
       ('gonbad-e-kavus', 'گنبد کاووس', ''),
       ('maragheh', 'مراغه', ''),
       ('babol', 'بابل', ''),
       ('mahabad', 'مهاباد', ''),
       ('sirjan', 'سیرجان', ''),
       ('qomsheh', 'قمصر', ''),
       ('marvdasht', 'مرودشت', ''),
       ('khoy', 'خوی', ''),
       ('bandar-e-mahshahr', 'بندر ماهشهر', ''),
       ('jahrom', 'جهرم', '');
