name: Check

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.4.1
        with:
          version: v1.64.5
          only-new-issues: true

  super-lint:
    name: Super Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CHECKOV: false
          VALIDATE_CSS: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_ENV: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_OPENAPI: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_TERRAFORM_TFLINT: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
